# Generated by Django 5.0 on 2023-12-17 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_description_alter_book_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='absolute_rating',
            new_name='total_rating',
        ),
    ]
